apache/rocketmq-mqtt

README.md
=> [ISSUE #4] Add license label in README file.

mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/WildcardManager.java, mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/TestWildcardManager.java
=> [ISSUE #6] Some code can be Optimize

.travis.yml, README.md
fix #20 add img and label for codeCov and build status in readme
=> [ISSUE #20]add img and label for codeCov and build status in readme

README.md
fix #26 add the refer to LMQ wiki and example
=> [ISSUE #26]add the refer to LMQ wiki and example

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/infly/MqttMsgId.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/infly/PushAction.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/store/LmqQueueStoreManager.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/upstream/processor/PublishProcessor.java
fix #31 Refactor some code and fix some bugs in high concurrency scenarios
=> [ISSUE #31] Refactor some code and fix some bugs

mqtt-common/src/test/java/org/apache/rocketmq/mqtt/common/test/TestMessageUtil.java, mqtt-common/src/test/java/org/apache/rocketmq/mqtt/common/test/TestNamespaceUtil.java
[ISSUE #40](https://github.com/apache/rocketmq-mqtt/issues/40) increase code coverage
=> Increase test case and improve code coverage

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/ChannelInfo.java
=> [ISSUE #53] fix ChannelInfo npe when clear method is called

README.md
=> add follow rocketmq logo

mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/protocol/mqtt/handler/TestMqttConnectHandler.java
=> [ISSUE #75]the unit test error in main

pom.xml
=> Bump logback-classic from 1.1.5 to 1.2.9

pom.xml
fix #106 fastjson deserialization arbitrary code execution security vulnerability
=> [ISSUE #106] fix fastjson update version to 1.2.83

meta/src/main/java/org/apache/rocketmq/mqtt/meta/raft/MqttRaftServer.java, meta/src/test/java/org/apache/rocketmq/mqtt/meta/raft/CounterClient.java
Unified Group ID separator to "%"
=> Unified Group ID separator

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/config/ConnectConf.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/facotry/MqttMessageFactory.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttConnectHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttPingHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttPubRecHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttPubRelHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttPublishHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttSubscribeHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttUnSubscribeHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/infly/PushAction.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/starter/MqttServer.java
add MqttMessageFactory and optimize codes.
=> add MqttMessageFactory and optimize codes.

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/handler/MqttPubRecHandler.java, mqtt-example/src/main/java/org/apache/rocketmq/mqtt/example/MqttConsumer.java, mqtt-example/src/main/java/org/apache/rocketmq/mqtt/example/MqttProducer.java
=> fix unit test

README.md
=> [ISSUE #163]Optimize format

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/loop/SessionLoopImpl.java
No need to persist offset , when cleansession is true
=> clean offset

mqtt-exporter/src/main/java/org/apache/rocketmq/mqtt/exporter/collector/MqttMetricsCollector.java
=> fix prometheus log error when set prometheus to false

README.md
=> fixNullPointInWill: should config meta addr in cs

pom.xml
[ISSUE #226 ]
pom文件中 logback1.2.3 与 logback1.2.9 冲突, remove logback1.2.3
=> Delete logback1.2.3 version conflict

mqtt-common/src/main/java/org/apache/rocketmq/mqtt/common/hook/AbstractUpstreamHook.java, mqtt-common/src/main/java/org/apache/rocketmq/mqtt/common/model/MqttMessageUpContext.java, mqtt-common/src/main/java/org/apache/rocketmq/mqtt/common/util/MessageUtil.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/ChannelInfo.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/ChannelManager.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/DefaultChannelManager.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/config/ConnectConf.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/MqttPacketDispatcher.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt/facotry/MqttMessageFactory.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/Mqtt5PacketDispatcher.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5ConnectHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5DisconnectHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PubRecHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PubRelHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PublishHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5SubscribeHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5UnSubscribeHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/infly/PushAction.java, mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/protocol/mqtt5/handler/TestMqtt5PublishHandler.java, mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/protocol/mqtt5/handler/TestMqtt5SubscribeHandler.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/upstream/mqtt5/processor/PublishProcessor5.java, mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/upstream/mqtt5/processor/TestPublishProcessor.java, mqtt-example/src/main/java/org/apache/rocketmq/mqtt/example/mqtt5/Mqtt5Consumer.java, mqtt-example/src/main/java/org/apache/rocketmq/mqtt/example/mqtt5/Mqtt5Producer.java
=> [ISSUE #241] support topic alias

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/starter/MqttServer.java
There is no need to duplicate Netty event loop for multiple passive listening socket.
=> feat: use shared Netty event loop for TCP/TCP over TLS/Web Socket

mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java, mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/meta/TestMetaPersistManagerSample.java
Close #264 
fix building error of UT and Checkstyle
UT
=> [ISSUE #264] fix(ds): fix building error of UT and Checkstyle

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/DefaultChannelManager.java, mqtt-exporter/src/main/java/org/apache/rocketmq/mqtt/exporter/collector/MqttMetricsCollector.java, mqtt-exporter/src/main/java/org/apache/rocketmq/mqtt/exporter/collector/MqttMetricsInfo.java
For #266 , add connections_size metric.
=> [ISSUE #266]: add connections_size metric

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/config/ConnectConf.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/loop/SessionLoopImpl.java
=> fix bug: PULL_EVENT not create when PULL_SUCCESS

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/loop/QueueCache.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/store/LmqQueueStoreManager.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/upstream/processor/PublishProcessor.java, mqtt-exporter/src/main/java/org/apache/rocketmq/mqtt/exporter/collector/MqttMetricsCollector.java, mqtt-exporter/src/main/java/org/apache/rocketmq/mqtt/exporter/collector/MqttMetricsInfo.java
Add metrics for topic dimension read and write msg size.
=> [ISSUE #266]: add metrics for topic dimension read and write msg size

distribution/conf/spring.xml, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/meta/MetaPersistManagerSample.java, mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java, mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/meta/TestMetaPersistManagerSample.java, mqtt-ds/src/test/java/org/apache/rocketmq/mqtt/ds/test/notify/TestNotifyManager.java
Fix #274 , develop branch startup exception.
=> [ISSUE #274]: fix startup exception

mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/ChannelManager.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/channel/DefaultChannelManager.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/config/ConnectConf.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5ConnectHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PubAckHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PubCompHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PubRelHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/protocol/mqtt5/handler/Mqtt5PublishHandler.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/Session.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/infly/PushAction.java, mqtt-cs/src/main/java/org/apache/rocketmq/mqtt/cs/session/loop/SessionLoopImpl.java, mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/channel/TestDefaultChannelManager.java, mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/session/TestSession.java
Close #246 
implement flow control for MQTT 5.0
UT
=> [ISSUE #246] feat: implement flow control

mqtt-cs/src/test/java/org/apache/rocketmq/mqtt/cs/test/channel/TestDefaultChannelManager.java
fix the UT of DefaultChannelManager
UT
=> [MINOR] improve: fix UT of DefaultChannelManager

README.md
add rocketmq version restrictions;
add prefix "$ROCKETMQ_HOME/bin/" in some rocketmq cmd;
fix "386" -> "x86" in Build Requirements.
=> add rocketmq version restrictions and update README --> develop

mqtt-ds/src/main/java/org/apache/rocketmq/mqtt/ds/notify/NotifyManager.java
=> fix NotifyManager refresh method throw MetaPersistManager NullPointerException
